## 标量

标量由只有一个元素的张量表示

In [1]:
import torch

x=torch.tensor([3.0])
y=torch.tensor([2.0])

x+y, x*y, x/y, x**y

(tensor([5.]), tensor([6.]), tensor([1.5000]), tensor([9.]))

## 向量

可以将向量视为标量值组成的列表

In [2]:
x=torch.arange(4)
x

tensor([0, 1, 2, 3])

可以通过张量的索引来访问任一元素

In [3]:
x[3]

tensor(3)

访问张量的长度，形状

> 这里可以看出，其实调用x.shap属性时，其实访问的是x.size()这个方法

In [7]:
len(x),x.shape,x.size()

(4, torch.Size([4]), torch.Size([4]))

## 矩阵

可以通过指定两个分量m和n来创建一个形状为m\*n的矩阵

In [8]:
A=torch.arange(20).reshape(5,4)

A.shape,A.size()

(torch.Size([5, 4]), torch.Size([5, 4]))

In [9]:
A.T

tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])

对称矩阵（symmetric matrix） 的转置等于本身

就像向量是标量的推广，矩阵是向量的推广一样，可以构建具有更多轴的数据结构

In [10]:
X=torch.arange(24).reshape(2,3,4)
X

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

行是最内侧的一维，也是reshape中的最后一个数字代表的维度

给定具有相同形状的任何两个张量，任何按元素二元运算的结果都将是相同形状的张量

In [23]:
A=torch.arange(20,dtype=torch.float32).reshape(5,4)
B=A.clone()

A,B

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]))

In [24]:
B[2,3]=0

In [25]:
B

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10.,  0.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])

In [26]:
A

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])

clone之后的张量修改，并不影响clone前的张量

+ 两个矩阵按元素乘法称为哈达玛积（Hadamard product），数学符号，⊙。虽然在计算机实现的时候，其实就是矩阵乘法，但是是和数学存在差异的
+ 与之对应的是标量和矩阵的运算，自动带有广播机制

In [27]:
A*B

tensor([[  0.,   1.,   4.,   9.],
        [ 16.,  25.,  36.,  49.],
        [ 64.,  81., 100.,   0.],
        [144., 169., 196., 225.],
        [256., 289., 324., 361.]])

相似的概念还有一个，点积（对应元素相乘的和），只适用于两个一维张量，不能是矩阵，否则会报错

**点积**：一维张量对应元素乘积的和

In [32]:
x=torch.tensor([1,2,3])
y=torch.tensor([3,4,5])
torch.dot(x,y)

tensor(26)

还有一个是矩阵和向量的乘法，要保证相乘的矩阵和向量的维度有一定的对应关系

**矩阵向量积Performs a matrix-vector product of the matrix**

In [41]:
A=torch.arange(20,dtype=torch.float32).reshape(4,5)
B=torch.ones(5)

A.size(), B.size(), torch.mv(A,B)

(torch.Size([4, 5]), torch.Size([5]), tensor([10., 35., 60., 85.]))

和mv（matrix-vector）矩阵向量乘积类似，还有**mm（matrix-martix）矩阵和矩阵的乘积**。

这里要求两个元素必须都是矩阵，没有办法一个矩阵，一个向量，向量自动扩展或者自动添加一个维度。

In [43]:
A=torch.arange(20,dtype=torch.float32).reshape(4,5)
B=torch.ones((5,1))
A,B,torch.mm(A,B)

(tensor([[ 0.,  1.,  2.,  3.,  4.],
         [ 5.,  6.,  7.,  8.,  9.],
         [10., 11., 12., 13., 14.],
         [15., 16., 17., 18., 19.]]),
 tensor([[1.],
         [1.],
         [1.],
         [1.],
         [1.]]),
 tensor([[10.],
         [35.],
         [60.],
         [85.]]))

计算元素的和

In [8]:
A.sum(),A.shape

(tensor(190.), torch.Size([5, 4]))

不管元素是什么样，sum的结果永远是一个标量，但是也可以指定轴

In [11]:
Asum=A.sum(axis=0)
Asum,Asum.shape

(tensor([40., 45., 50., 55.]), torch.Size([4]))

在这里可以看出，
+ 对axis=0，对最外层求和，就会把这层去掉
+ 对axis=0,1，就会逐层求和，最后效果就等于A.sum()

求均值

In [12]:
A.mean(),A.sum()/A.numel()

(tensor(9.5000), tensor(9.5000))

不仅可以对整体求均值，也可以对特定的轴求均值

In [13]:
A.mean(axis=0),A.sum(axis=0)/A.shape[0]

(tensor([ 8.,  9., 10., 11.]), tensor([ 8.,  9., 10., 11.]))

也可以通过添加参数保持轴数不变

In [14]:
A.sum(axis=1,keepdims=True)

tensor([[ 6.],
        [22.],
        [38.],
        [54.],
        [70.]])

In [15]:
A.sum(axis=1)

tensor([ 6., 22., 38., 54., 70.])

使用keepdims的好处在于，后续可以使用广播操作。

**但是自己实际跑下来，似乎不用保持维度数量一致，也可以使用广播机制**

比如：`A/sum_A` 要求A和sum_A维度相同（都是二维，不然没法扩展）

不去管数字\*矩阵，这里矩阵\*矩阵或者矩阵\*向量，要求二者维度相同，到达最里层元素的中括号数量相同

In [19]:
A, Asum, A/Asum

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([40., 45., 50., 55.]),
 tensor([[0.0000, 0.0222, 0.0400, 0.0545],
         [0.1000, 0.1111, 0.1200, 0.1273],
         [0.2000, 0.2000, 0.2000, 0.2000],
         [0.3000, 0.2889, 0.2800, 0.2727],
         [0.4000, 0.3778, 0.3600, 0.3455]]))

沿着某个轴计算`A`元素的累计总合

In [21]:
A.cumsum(axis=0)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  6.,  8., 10.],
        [12., 15., 18., 21.],
        [24., 28., 32., 36.],
        [40., 45., 50., 55.]])

+ 和上面打印的A对比一下，axis=0，就是竖着方向
+ 对于第一列，第一个数字是0，第二个数字是4（0+4），第三个数字是12（0—+4+8），第四个数字是24（0+4+8+12），就像斐波那契数列一样，当前元素等于前两个元素之和

## **范数**

+ L2范数是向量元素平方和的平方根

In [44]:
u=torch.tensor([3.0,4.0])
torch.norm(u)

tensor(5.)

+ L1范数，表示为向量元素的绝对值之和(torch并没有对L1范式给一个标准的求解方式，可以自己通过绝对值与和两种运算去计算)

In [45]:
torch.abs(u).sum()

tensor(7.)

+ F范数，矩阵的佛罗贝尼乌斯范式是：矩阵元素平方和的平方根

In [46]:
torch.norm(torch.ones(4,9))

tensor(6.)

根号下36=6