**不显示科学计数法**

In [1]:
import numpy as np
np.set_printoptions(suppress=True,   precision=20,  threshold=10,  linewidth=40)

In [2]:
import torch

**张量表示一个数值组成的数组，这个数组可能有多个维度**

In [91]:
x=torch.arange(12)
print(x)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])


In [92]:
x.shape

torch.Size([12])

In [93]:
x.ndim

1

**number of element 永远是一个标量**

In [5]:
x.numel()

12

In [94]:
y=torch.zeros(3,4)
print(y,"\n",y.numel())

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]) 
 12


In [95]:
y.ndim

2

## reshape和view的区别

**reshape 维度从最外层开始**

In [9]:
X=x.reshape(3,2,2)
X

tensor([[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]],

        [[ 8,  9],
         [10, 11]]])

In [19]:
X.shape

torch.Size([3, 2, 2])

In [24]:
Y=x.view(size=(3,2,2))

**permute 重新排序**

张量数值连续（不是整数，是小数时）

In [3]:
import torch

In [4]:
a=torch.rand(3,3)
b=a.permute(1,0)

In [5]:
c=b.reshape((3,3))
c[0]=100
c,b

(tensor([[100.0000, 100.0000, 100.0000],
         [  0.1986,   0.8549,   0.3612],
         [  0.1078,   0.3518,   0.9700]]),
 tensor([[100.0000, 100.0000, 100.0000],
         [  0.1986,   0.8549,   0.3612],
         [  0.1078,   0.3518,   0.9700]]))

In [6]:
id(c),id(a),id(b)

(2287353781528, 2287276327784, 2287277338120)

In [7]:
d=torch.arange(9)
e=d.reshape(3,3)
# c[0]=100
d[:]=100
d,e

(tensor([100, 100, 100, 100, 100, 100, 100, 100, 100]),
 tensor([[100, 100, 100],
         [100, 100, 100],
         [100, 100, 100]]))

In [8]:
id(d),id(e)

(2287353854616, 2287353853816)

**如果是直接定义，则reshape和view前后的变量是浅复制，会互相影响。**

In [11]:
cv=b.view(3,3)
cv[0]=20
cv,b

(tensor([[20.0000, 20.0000, 20.0000],
         [ 0.1986,  0.8549,  0.3612],
         [ 0.1078,  0.3518,  0.9700]]),
 tensor([[20.0000, 20.0000, 20.0000],
         [ 0.1986,  0.8549,  0.3612],
         [ 0.1078,  0.3518,  0.9700]]))

**但是对于view来说，则会影响，与变量中数值是否连续/离散无关**

In [88]:
a1=torch.tensor([[1,2,3],[11,12,13]])
b1=a1.permute(1,0)
# 把之前的1维放到现在的0维，之前的0维放到现在的1维

In [90]:
c1=b1.reshape(6)
c1[0]=100
c1,b1

(tensor([100,  11,   2,  12,   3,  13]),
 tensor([[ 1, 11],
         [ 2, 12],
         [ 3, 13]]))

In [91]:
cv1=a1.view(6)
cv1[0]=100
cv1,a1

(tensor([100,   2,   3,  11,  12,  13]),
 tensor([[100,   2,   3],
         [ 11,  12,  13]]))

> 对使用`reshape`方法得到的变量进行值的更新，不会影响reshape前的变量
但是如果使用`view`方法，则会影响reshape前的变量

## 其他

**使用全0、全1、其他常量或者从特定分布中随机采样的数字**

这类函数的size可以使用类似list或者tuple的形式来表示，可以看到以下三种写法的结果是一致的。

In [10]:
torch.zeros((2,3,4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [14]:
torc
h.zeros([2,3,4])

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [15]:
torch.zeros(2,3,4)

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [16]:
torch.ones([2,3,4])

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [17]:
torch.randint(low=0,high=20,size=(2,2,2))

tensor([[[ 6, 16],
         [ 8, 15]],

        [[ 4,  1],
         [10,  9]]])

**通过提供包含数值的python列表（或嵌套列表）来为所需张量中的每个元素赋予确定值**

In [18]:
torch.tensor([[[1,2],[234,345]],[[123,23],[234,134]]])

tensor([[[  1,   2],
         [234, 345]],

        [[123,  23],
         [234, 134]]])

## 数学运算

**常见的标准算术运算符（`+`,`-`,`*`,`/`和`**`）都可以被升级为按元素运算**

In [93]:
x=torch.tensor([1.0,2,4,8])
y=torch.tensor([2,2,2,2])
x+y,x-y,x*y,x/y,x**y

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

### 广播机制

**带有自动广播机制 broadcasting mechanism**

In [2]:
a=torch.arange(3).reshape((3,1))
b=torch.arange(2).reshape((1,2))

In [4]:
a,b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

当两个维度不同的向量进行数学运算时，会自动进行广播。
即，a会自动扩展为一个(3,2)维度的向量，而b会自动扩展为一个(3,2)维度的向量，然后维度一致，就可以进行对应位置元素相加了。
```python
a=tensor([[0,0],
         [1,1],
         [2,2]]
b=tensor([[0, 1],
          [0, 1]
          [0, 1]])
```

In [3]:
a+b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

In [94]:
2*x

tensor([ 2.,  4.,  8., 16.])

In [96]:
torch.tensor([2,2])*x
# non-singleton 非单例

RuntimeError: The size of tensor a (2) must match the size of tensor b (4) at non-singleton dimension 0

按照元素进行指数运算

In [97]:
torch.exp(x)

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

## 其他常见张量操作

### 连接

In [6]:
X=torch.arange(12,dtype=torch.float32).reshape((3,4))

In [7]:
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [13]:
Y=torch.tensor([[2.0,1,4,3],[1,2,3,4],[4,3,2,1]])

In [14]:
Y

tensor([[2., 1., 4., 3.],
        [1., 2., 3., 4.],
        [4., 3., 2., 1.]])

In [6]:
torch.cat((X,Y),dim=0)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [ 2.,  1.,  4.,  3.],
        [ 1.,  2.,  3.,  4.],
        [ 4.,  3.,  2.,  1.]])

In [7]:
torch.cat((X,Y),dim=1)

tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
        [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
        [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]])

**通过逻辑运算符构建二元张量**

In [8]:
X==Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

**对张量中的所有元素进行求和会产生只有一个元素的张量**

In [9]:
X.sum()

tensor(66.)

In [8]:
X[0:2,:]=12
X

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

In [9]:
alist=[0,1,2,3,4]
alist[:3]

[0, 1, 2]

In [12]:
a=list(range(5))
a

[0, 1, 2, 3, 4]

可以看到不管是切片，还是range，都是左闭右开。alist[:3]只能取到索引为0,1,2的元素，取不到3

### 操作重新分配内存

**运行一些操作可能为导致为新结果分配内存**

`id()`函数，返回该对象的内存标识
Return the identity of an object.

This is guaranteed to be unique among simultaneously existing objects.
(CPython uses the object's memory address.)

返回一个对象的id，同时保证已存在的对象的id都唯一，CPython使用对象的内存地址。

In [16]:
before=id(Y)
before

2058886871064

In [17]:
Y=Y+X
id(Y)

2058886886488

In [18]:
id(Y)==before

False

可以看到，执行加法操作之后，分配了新的内存

In [19]:
Y.shape

torch.Size([3, 4])

In [21]:
Y=Y.reshape([2,6])

In [22]:
id(Y)

2058886886168

reshape之后，也是重新分配内存

In [23]:
Y=Y.view([4,3])

In [24]:
id(Y)

2058886558008

view操作之后，也会重新分配内存。。。。

### 原地操作的函数

In [28]:
X=torch.arange(12,dtype=torch.float32).reshape((3,4))
Y=torch.tensor([[2.0,1,4,3],[1,2,3,4],[4,3,2,1]])

In [29]:
Y

tensor([[2., 1., 4., 3.],
        [1., 2., 3., 4.],
        [4., 3., 2., 1.]])

zeros_like，生成的张量和参数给出的张量shape相同，数值全为0

In [30]:
Z=torch.zeros_like(Y)
print(f"Z的id是：{id(Z)}")
Z[:]=X+Y
print(f"Z的id是：{id(Z)}")
print(f"Y的id是：{id(Y)}")

Z的id是：2058886841432
Z的id是：2058886841432
Y的id是：2058887002296


In [32]:
Z=Z+1
id(Z)

2058886841032

确实这样生成的张量，内存空间一直不变。

如果后续计算中没有重复使用X，也可以使用以下方式来减小操作的内存开销

**X+=Y和X[:]=X+Y都是原地操作**

In [33]:
before=id(X)
X+=Y
id(X)==before

True

In [34]:
before=id(X)
X[:]=X+Y
id(X)==before

True

In [35]:
before=id(X)
X=X+Y
id(X)==before

False

**结论**
> 1. 表现为对应元素相加，则就会进行原地操作，根据博客[pytorch中 += 操作被视为是原地操作](https://blog.csdn.net/m0_46653437/article/details/113528037)
  2. 如果可能利用到了广播机制，则会分配新的内存
  3. 另外，根据[Pytorch里运算符*=和+=之异同](https://zhuanlan.zhihu.com/p/34609744)，在下面同样进行了测试和说明，这个博客的例子很好，但是解释的很烂，请看下面我的验证。

In [41]:
aa=torch.FloatTensor([[1,2],[3,4]])
print(f"aa的id为{id(aa)}")
bb=aa
print(f"bb修改前的id为{id(bb)}")
bb=bb*2
print(f"bb修改后的id为{id(bb)}")
print(aa)
print(bb)

aa的id为2058908882648
bb修改前的id为2058908882648
bb修改后的id为2058908870040
tensor([[1., 2.],
        [3., 4.]])
tensor([[2., 4.],
        [6., 8.]])


从上面的id变化情况可以看出，
+ pytorch的`赋值=`都是`浅拷贝`,虽然多了一个bb变量，但是它和aa变量都指向同一片内存区域。
+ bb\*2之后开辟了一个新的内存区域，所以bb值发生了变化。

In [42]:
cc=torch.FloatTensor([[1,2],[3,4]])
print(f"cc的id为{id(cc)}")
dd=cc
print(f"dd修改前的id为{id(dd)}")
dd*=2
print(f"dd修改后的id为{id(dd)}")
print(f"dd修改后cc的id为{id(cc)}")
print(cc)
print(dd)

cc的id为2058909278600
dd修改前的id为2058909278600
dd修改后的id为2058909278600
dd修改后cc的id为2058909278600
tensor([[2., 4.],
        [6., 8.]])
tensor([[2., 4.],
        [6., 8.]])


从上面的id变化情况可以看出，
+ 赋值操作是浅拷贝，所以dd经由cc赋值后，二者id相同，都是同一片区域
+ 之后dd*=2，`*=`是`in-place`操作符，所以对cc和dd共同指向的那片内存的值进行了修改，进而dd的值就影响了cc，二者指向的是同一片内存区域

仿照[pytorch中的ReLU与inplace原地操作的一些注意点](https://zhuanlan.zhihu.com/p/350316775)最后变量的指向引用图画出来上面问题的图解：

官方文档关于原地操作运算的说明：
+ https://discuss.pytorch.org/t/what-is-in-place-operation/16244/2
+ https://pytorch.org/tutorials/beginner/blitz/tensor_tutorial.html#operations
+ 官网文档的中文翻译：[PyTorch中in-place](https://blog.csdn.net/qq_38163755/article/details/87905524)

## numpy和torch转换

In [44]:
A=X.numpy()
B=torch.tensor(A)
type(A),type(B)

(numpy.ndarray, torch.Tensor)

将大小为1的张量转换为python标量

In [45]:
a=torch.tensor([3.5])
a,a.item(),float(a),int(a)

(tensor([3.5000]), 3.5, 3.5, 3)

In [50]:
a.numel()

1

In [46]:
b=torch.tensor([3.5,2.0])

In [47]:
b.item()

ValueError: only one element tensors can be converted to Python scalars

所以这个item()函数专用于获取大小为1的张量，将其转换为python标量

In [49]:
b.numel()

2

## Q&A

**tensor和array的区别？**
>+ tensor是一个数学概念，张量，数学上的明确定义。
>+ array是计算机里的一个语言，数组，numpy中的ndarray，n-dimension array，n维的数组。
>+ pytorch和tensorflow重载了数学中张量的概念，

可以去看看，[百度百科词条张量](https://baike.baidu.com/item/%E5%BC%A0%E9%87%8F/380114?fr=aladdin)